define(['backbone', 'collections/targets'], function (Backbone, Targets) {
	/**
		 Game model. Keeps info about score, manages targets, etc.

		 The model has "started/stopped" state. When the game is started by `start` method, `started` field is `true` and new targets are continuously generated by `sleepAndCreateTarget` method.
	 */
	return Backbone.Model.extend({
		initialize: function () {
			_.bindAll(this, 'onCreateTarget');
		},
		
		onCreateTarget: function () {
			if (this.started) {
				this.targets.create();
				this.sleepAndCreateTarget();
			}
		},
		
		sleepAndCreateTarget: function () {
			setTimeout(this.onCreateTarget, Math.random() * 500);
		},

		start: function () {
			this.started = true;
			this.targets = new Targets();
			this.sleepAndCreateTarget();
		},

		stop: function () {
			this.started = false;
		}
	});
});
